name: Build iOS
on:
workflow_dispatch:
jobs:
build:
runs-on: macos-14
steps:
- uses: actions/checkout@v4
- uses: actions/setup-node@v4
with:
node-version: "18"
- run: npm install -g pnpm
- run: pnpm install
- run: npx cap sync ios
- run: cd ios/App && pod install
- run: |
xcodebuild \
-workspace ios/App/App.xcworkspace \
-scheme App \
-sdk iphoneos \
-configuration Release \
build \
CODE_SIGNING_ALLOWED=NO \
CODE_SIGNING_REQUIRED=NO \
CODE_SIGN_IDENTITY=""
