name: iOS
on:
workflow_dispatch:
jobs:
build:
runs-on: macos-14
steps:
- name: Checkout
uses: actions/checkout@v4
- name: Setup Node
uses: actions/setup-node@v4
with:
node-version: "18"
- name: Install pnpm
run: npm install -g pnpm
- name: Install deps
run: pnpm install
- name: Cap sync
run: npx cap sync ios
- name: Disable Signing
run: |
sed -i '' 's/ProvisioningStyle = Automatic;/ProvisioningStyle = Manual;/g' ios/App/App.xcodeproj/project.pbxproj
sed -i '' 's/DEVELOPMENT_TEAM = [A-Z0-9]*;//g' ios/App/App.xcodeproj/project.pbxproj
- name: Pod install
run: cd ios/App && pod install
- name: Build iOS
run: |
xcodebuild -workspace ios/App/App.xcworkspace \
-scheme App \
-sdk iphoneos \
-configuration Release \
build \
CODE_SIGNING_ALLOWED=NO \
CODE_SIGNING_REQUIRED=NO \
CODE_SIGN_IDENTITY=""

